name: "[Release] Release to npm"

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: "1"
  NPM_REGISTRY: ${{ vars.NPM_REGISTRY }}

## TODO: PLUG JFROG

jobs:
  build-and-attest:
    runs-on: ubuntu-22.04
    environment: Production
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
      pull-requests: write
      # Need to attest artifacts
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-action-composite
      - name: build libraries
        run: pnpm nx run-many -t build --projects=ledger-button,ledger-button-core

      - name: Login to internal JFrog registry
        id: jfrog-login
        uses: LedgerHQ/actions-security/actions/jfrog-login@actions/jfrog-login-1

      - name: Setup npm config for JFrog
        env:
          NPM_REGISTRY_TOKEN: ${{ steps.jfrog-login.outputs.oidc-token }}
        run: |
          cat << EOF | tee .npmrc
          registry=https://${NPM_REGISTRY}/
          //${NPM_REGISTRY}/:_authToken=${NPM_REGISTRY_TOKEN}
          EOF

      # See if we can rework this to crawl the monorepo and get the tarball for each package
      - name: Create dist directory to store tarball
        run: mkdir -p dist

      - name: release to npm
        run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Get tarball for each package
        run: |
          find . -name "ledgerhq-*.tgz" -exec cp {} ./dist \;

      - name: Attest tarball
        uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
        with:
          subject-path: ./dist

      # The action currently doesn't support pushing the blob to the registry
      - name: Sign tarball
        uses: LedgerHQ/actions-security/actions/sign-blob@actions/sign-blob-1
        with:
          path: ./dist

      - name: Upload packages to GitHub Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: npm-snapshot-packages
          path: dist/*.tgz
          retention-days: 1
          if-no-files-found: error

      - name: Publish to Github Release
        uses: LedgerHQ/actions-security/actions/create-github-release@create-github-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  ledger-runner:
    name: Publish NPM packages to JFrog
    needs: build-and-attest
    runs-on: public-ledgerhq-shared-medium
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.REF }}

      - uses: ./.github/actions/setup-action-composite
        with:
          playwright: false

      - name: Download packages from GitHub Artifacts
        uses: actions/download-artifact@v7
        with:
          name: npm-release-packages
          path: dist

      - name: Publish snapshot packages to JFrog
        uses: ./.github/actions/publish-to-jfrog-composite
        with:
          npm-registry: ${{ env.NPM_REGISTRY }}
          dist-path: dist
